name: pangeo
channels:
  - conda-forge
  - anaconda
dependencies:
  - pangeo-notebook
  - xarray
  - intake-xarray
  - nb_black
  - pip
  - gcsfs
  - zarr
  - intake
  - nc-time-axis
  - seaborn
  # regridding
  - esmpy=7.1.0
  - xesmf
  # vis
  - matplotlib
  - graphviz
  - python-graphviz
  - cartopy  # mapping
  - pip:
    - git+https://github.com/bradyrx/climpred.git
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/jbusecke/cmip6_preprocessing.git
    - git+https://github.com/mathause/regionmask.git
